### ISSUE TITLE
Eliminate Orphaned Includes

### ISSUE THREAD

**Issue by arnavs** [ubcecon/lecture-source-jl#4]
As discussed, code that's not repeated should be moved out of the `_static/code` folder or whatever it's called.

**Comment by arnavs** [comment]
Also I think we should rename the `lecture_howto_jl.raw` file to something more meaningful (and not `.raw`, since it's just a text file with some HTML?). It looks like this is the header that we put at the top of every lecture, so `julia_header.txt` seems like it'd do the job...

**Comment by jlperla** [comment]
Another related issue may be to completely nuke files that are not used at all. Including files merged in after this task
