### ISSUE TITLE
Replace REPL Screenshots with Text

### ISSUE THREAD

**Issue by arnavs** [ubcecon/lecture-source-jl#5]
IMO, there's no reason to use a REPL screenshot. It bloats up the repo, and makes it much harder to update.

**Comment by jlperla** [comment]
I don't know... There are lots of times when it is helpful for beginners... Depends i on the context.

**Comment by arnavs** [comment]
I guess I wonder what this can do:

<img width="871" alt="screen shot 2018-08-24 at 4 09 49 pm" src="https://user-images.githubusercontent.com/5009477/44611767-24eaf880-a7b8-11e8-9a70-00b4fa900704.png">

That this can't do:

```
arnavsood@Arnavs-MacBook-Pro:~/research/lecture-source-jl$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.0.0 (2018-08-08)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> 
```

**Comment by jlperla** [comment]
I hear you... That is nice because it shows the full text.

**Comment by Nosferican** [comment]
@arnavs could you post the suitable RST code for it to display properly in Jupyter notebooks, HTML, TeX?
